package com.ecom.orderservice.controller;

import com.ecom.orderservice.dto.CreateOrderRequest;
import com.ecom.orderservice.dto.OrderResponse;
import com.ecom.orderservice.dto.OrderResult;
import com.ecom.orderservice.service.OrderService;
import jakarta.validation.Valid;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.UUID;

@Slf4j
@RestController
@RequestMapping("/orders")
@RequiredArgsConstructor
public class OrderController {

    private static final String IDEMPOTENCY_HEADER = "X-Idempotency-Key";

    private final OrderService orderService;

    @PostMapping
    public ResponseEntity<OrderResponse> createOrder(
            @Valid @RequestBody CreateOrderRequest request,
            @RequestHeader(IDEMPOTENCY_HEADER) String idempotencyKey) {

        // JDK 10 — var: compiler infers OrderResult
        var result = orderService.createOrder(request, idempotencyKey);

        // JDK 21 — Pattern matching in switch with guard (JEP 441, finalized JDK 21).
        // `case OrderResult r when r.isDuplicate()` binds the value to r, then applies the guard.
        // isDuplicate() is generated by Lombok @Value for the boolean field (Java bean convention).
        // `default` catches the non-duplicate case — required because OrderResult is not sealed.
        var status = switch (result) {
            case OrderResult r when r.isDuplicate() -> HttpStatus.OK;      // idempotent replay
            default                                 -> HttpStatus.CREATED; // new order
        };

        return ResponseEntity.status(status).body(result.getOrder());
    }

    @GetMapping("/{id}")
    public ResponseEntity<OrderResponse> getOrder(@PathVariable UUID id) {
        return ResponseEntity.ok(orderService.getOrder(id));
    }
}
